### ISSUE TITLE
Creo que hay que hacer una corrección:

### ISSUE THREAD

**Issue by Vodker** [kcdtv/nmk#1]
Línea 144:
 D7=$(printf '0x%X\n' $(( 0x$K1 ^ 0x$(echo $serial | cut -c 2))) | cut -c 3)
Cambiar por
 D7=$(printf '0x%X\n' $(( 0x$K1 ^ 0x$(echo $seri | cut -c 2))) | cut -c 3)

Saludos.

**Comment by kcdtv** [comment]
Gracias. :smiley_cat:
corregido en  793003d8c1acd4bc12440836f8cad4f559911fd9

**Comment by PASTO666** [comment]
adaptador awus036ac sin la h también usa el mismo chipset (8812au) y cuesta aun menos que el que es h. Es para dejarle saber. Y gracias. El awus036ach tiene buen power y alcanze!! Se lo recomiendo no se va a decepcionar con el :) vodker
