### ISSUE TITLE
linea 51 , revision de wash

### ISSUE THREAD

**Issue by wifislax-ng** [kcdtv/nmk#2]
Holas, donde revisa las versiones de los ejecutables , arreglaste en lo de comprobar version reaver , pero te falto donde revisa wash añadir la 1.6.5 o se sale aunque tengas version mas nueva

**Comment by wifislax-ng** [comment]
Para no tener que estas manteniendo esa parte del code , podrias hacer una comparacion ..y si es menor a 163 , ..pues error

if (($version > 163 )); then
echo Error ....
fi

ya sabes, grepeas el numero entero y le quitas los puntos ...

**Comment by kcdtv** [comment]
Ups.... gracias por señalar este error. :smiley_cat:  
Fixed with  https://github.com/kcdtv/nmk/commit/ab6167e09824ab7ee5500e303eca394d97c992b7
